### ISSUE TITLE
first version

### ISSUE THREAD

**Issue by ivotron** [getpopper/website#1]
This new website is using Hugo and the Docsy theme, and it's built/deployed/tested as described in the README.

For this issue, we'll work on having a basic landing page with links to [documentation](https://popper.rtfd.io), [blog](http://medium.com/getpopper), [repo](https://github.com/getpopper/popper), [slack](https://join.slack.com/t/getpopper/shared_invite/zt-dtn0se2s-c50myMHNpeoikQXDeNbPew), [twitter](https://twitter.com/getpopper), [google groups](https://groups.google.com/g/getpopper) that is served at https://getpopper.github.io/website

**Comment by FernandaDguez** [comment]
I would like to work on this

**Comment by ivotron** [comment]
awesome, thanks a lot!

**Comment by ivotron** [comment]
closed by https://github.com/getpopper/website/pull/2
